Feat/create mise en place role
elhub/devxp-ansible-collection-wsl pull request #44
Opened 2024-12-20 11:33 UTC by lise-may-le-statnett

2024-12-20 12:17 UTC, henrik-fauskanger-statnett approved these changes

2024-12-20 13:29 UTC, lise-may-le-statnett commented on README.md
> +* **mise** dole: See documentation [here](https://github.com/elhub/devxp-ansible-collection-wsl/blob/main/roles/mise/README.md)
Fixed!

2024-12-20 13:29 UTC, lise-may-le-statnett commented on roles/mise/.yamllint
Removed this file

2024-12-20 13:30 UTC, lise-may-le-statnett commented on roles/mise/README.md
> +We will use mise to install Kubernetes tools, i.e. kubectl and helm.
Removed the sentence

2024-12-20 13:31 UTC, lise-may-le-statnett commented on roles/mise/README.md
> +*  [Activate mise](https://mise.jdx.dev/getting-started.html#_2-activate-mise)
Removed extra space

2024-12-20 13:31 UTC, lise-may-le-statnett commented on roles/mise/README.md
> +    - elhub.ansible_collection_wsl
Corrected collections reference. Also fixed this for the other roles as well

2024-12-20 13:32 UTC, lise-may-le-statnett commented on roles/mise/meta/main.yml
> +        - focal
Corrected :)

2024-12-20 13:32 UTC, lise-may-le-statnett commented on roles/mise/defaults/main.yaml
> +mise_path: "{{ ansible_env.HOME }}/.local/bin/mise"
Added!

2024-12-20 13:36 UTC, lise-may-le-statnett commented on roles/mise/tasks/main.yaml
> +      script_shell="$(readlink /proc/$$/exe | sed "s/.*\///")"
Edited :)

2025-01-02 07:50 UTC, krilor requested changes
We are pretty close. Requesting changes for non-NIT comments.

2025-01-02 07:50 UTC, krilor commented on roles/mise/defaults/main.yaml
> +mise_path: "{{ ansible_env.HOME }}/.local/bin/mise"
This doesn't seem right given the recent changes to the role (apt stuff)

2025-01-02 07:50 UTC, krilor commented on roles/mise/tasks/main.yaml
> +    update_cache: true
This task is not needed as it is also in line 36 (the next task)

2025-01-02 07:50 UTC, krilor commented on roles/mise/tasks/main.yaml
> +    update_cache: yes
NIT: Try not to use yes/no - use true/false for bools.

2025-01-02 07:50 UTC, krilor commented on roles/mise/tasks/main.yaml
> +    dest: "{{ ansible_env.HOME }}/.shrc.d/60-mise.sh"
NIT: We can consider using the `.bash` and `.zsh` extensions instead.

Ref https://github.com/elhub/devxp-ansible-collection-wsl/blob/main/roles/shellrc/README.md

> The different shells will source the files in the shrc.d directory based on the file extensions.
>
>   .sh - sourced by both bash and zsh
>    .bash - sourced by bash
>    .zsh - sourced by zsh
>

2025-01-02 11:17 UTC, lise-may-le-statnett commented on roles/mise/tasks/main.yaml
> +  ansible.builtin.shell: curl https://mise.run | sh
Agree! I pushed a commit where the mentioned Ubuntu guidelines are now followed :)

2025-01-02 11:19 UTC, lise-may-le-statnett commented on roles/mise/defaults/main.yaml
> +mise_path: "{{ ansible_env.HOME }}/.local/bin/mise"
Yes, this path is never used. I have now removed it

2025-01-02 11:20 UTC, lise-may-le-statnett commented on roles/mise/tasks/main.yaml
> +  ansible.builtin.shell: curl https://mise.run | sh
Will also soon commit change where the repo is added to https://github.com/elhub/devxp-wsl/blob/main/templates/apt/unattended-upgrades.j2#L21-L31

2025-01-02 11:26 UTC, krilor commented on roles/mise/tasks/main.yaml
> +    echo "{{ gpg_key_content.content }}" | gpg --dearmor | tee /etc/apt/keyrings/mise-archive-keyring.gpg > /dev/null
This step is not idempotent. Should we add a "creates"  or "changed_when" or "when"?

Also consider doing dearmor in a similar way as https://github.com/elhub/devxp-ansible-collection-wsl/blob/main/roles/opentofu/tasks/main.yml#L11-L25 ? Handling things in a somewhat similar way is benefitial for future maintainers of this collection.

2025-01-02 11:27 UTC, krilor commented on roles/mise/tasks/main.yaml
> +  register: gpg_key_content
We generally prefix variables with role name to avoid conflicts.
Super-local variables like this one should also have a starting underscore to indicate that is it just used here.

So `_mise_gpg_key` (removed _content to avoid stutter like _content.content)

2025-01-02 12:21 UTC, lise-may-le-statnett commented on roles/mise/tasks/main.yaml
> +    update_cache: true
Removed!

2025-01-02 12:24 UTC, lise-may-le-statnett commented on roles/mise/tasks/main.yaml
> +    update_cache: yes
Fixed!

2025-01-02 12:42 UTC, lise-may-le-statnett commented on roles/mise/tasks/main.yaml
> +    dest: "{{ ansible_env.HOME }}/.shrc.d/60-mise.sh"
Agree, using `.bash` and `.zsh` extensions instead explicitly configures the PATH for both bash and zsh shells. I have now split this into two tasks: one for bash and another for zsh

2025-01-02 13:32 UTC, lise-may-le-statnett commented on roles/mise/tasks/main.yaml
> +    echo "{{ gpg_key_content.content }}" | gpg --dearmor | tee /etc/apt/keyrings/mise-archive-keyring.gpg > /dev/null
I have now changed it to align with the playbook for opentofu. Using the `creates ` parameter ensures the task is idempotent

2025-01-02 13:37 UTC, lise-may-le-statnett commented on roles/mise/tasks/main.yaml
> +  register: gpg_key_content
This variable is no longer used and will be deleted. Appreciate the input, will make sure to remember this for next time :)

2025-01-02 14:04 UTC, krilor commented on roles/mise/tasks/main.yaml
> +  ansible.builtin.command: dpkg --print-architecture
NIT: This seems unneccessary since we are targeting WSL2 Ubuntu24?

2025-01-02 14:05 UTC, krilor commented on roles/mise/tasks/main.yaml
> +    update_cache: true
Isn't it still here?

2025-01-02 14:06 UTC, lise-may-le-statnett commented on roles/mise/tasks/main.yaml
> +  ansible.builtin.command: dpkg --print-architecture
Heh you're right, will remove this 👍

2025-01-02 15:06 UTC, krilor approved these changes
Sweet!

2025-01-02 15:09 UTC, merged